### ISSUE TITLE
江苏中铁网络科技开发有限公司

### ISSUE THREAD

**Issue by H5DevHoward** [JoshuaYang/interview-black-list#1]
名称：江苏中铁网络科技开发有限公司
面试地点：苏州市相城区采莲路1037-1039
说明：你一旦投了简历，会有邮件通知你到苏州统一面试，地址是苏州市相城区采莲路1037-1039，面试时间是上午8：00-10：00[被坑网友自述](https://tieba.baidu.com/p/5179559731)

**Comment by JoshuaYang** [comment]
已更新
