### ISSUE TITLE
快乐说教育科技

### ISSUE THREAD

**Issue by H5DevHoward** [JoshuaYang/interview-black-list#2]
1. 公司名称：快乐说教育科技
2.地址：无锡梁溪区无锡市教育评估院扬名新村720号（技师学院内 传达室二楼）
3.说明：我是去面试前端开发的。那天提前到的，打了电话 说马上来 然后等了会儿，看到他的时候 他在打电话 “好的好的，xx项目，balabla，我这边还有点事，先就这样”，我就有种奇怪的感觉 像是做戏给我看，很做作，然后带我去办公室——两个房间，50平米左右，当时九点多了 一个人都没有来上班，他跟我解释这只是一个分部，还有一个在中智培训那边，中智会计那块balabala都是他公司做的，然后说YY跟他也有合作，项目金额还不小，然后说“你去看看那些，都是我们做的”，我说看啥，他指了指一堆会计相关资料。。。我是去面试前端的 让我看这些干嘛？很奇怪，然后他就掏出了他的笔记本，给我看他们官网（有点会计在线教育的样子），说这是挂他的服务器，他是设计出身，然后说之后这个项目要做自适应，balaba，还给我看了网站的架构图，说他们要找的前端是设计+开发一体，一个人做。然后我就更烦躁了，根本不想待在这，他期间还打了好几个电话，说是打给公司某技术负责人，然他早点过来上班，还打电话说是个前端开发的，balabala，就是很烦躁。我还以为进了传销，可怕，最后给他看了些我的项目，他说这个特效是不是拖了什么插件 = = 呵呵，还说这种管理系统 很简单的 稍微有点基础的都能做出来。然后给我看他们的管理系统，说这个这个很厉害什么的，我说对啊 这也是个管理系统，他就说这个很难 很复杂，说有接口免费提供给他们，然后我说这个很简单啊 就一些表单 多级目录，我说我就是干这个的啊 你以为前端开发是怎么做管理系统的。很无语。。总要表现的自己懂点技术，我很尴尬。因为他一直打电话，这种面试居然拖了近50分钟，越来越烦躁，然后我就说你们公司跟我设想的开发流程差距很大，接受不了，我就找个借口要跑路。还好 他估计我也烦躁了，没太过废话

**Comment by JoshuaYang** [comment]
已更新
