### ISSUE TITLE
无锡洁澄水业

### ISSUE THREAD

**Issue by ekkoJ** [JoshuaYang/interview-black-list#4]
公司里面装修的挺不错，进去以后一个地中海大叔面的，技术方面就谈了一分钟左右，问我会不会原生JS，会不会h5 css3，问完以后就开始不断介绍他们的产品，他们水怎么怎么样，然后那个袋装水卖的怎么怎么好，饮水机红木的~怎么怎么厉害~，然后又说他们现在IT部门正在重组，目前人数不多，之后肯定是要独立出来成为一个新的公司的，说注册都注册好了，现在进来就是首批员工，能有股权，然后现在这个公司那么多客户，因为这么多客户然后会有多少的流量啊关注度啊，然后说你看多有钱途啊之类的巴拉巴拉一大堆大饼画的贼大，整整扯了一个多钟头，困得要死。

**Comment by JoshuaYang** [comment]
公司名：江苏洁澄水业科技有限公司
地址：金石路545号

**Comment by JoshuaYang** [comment]
已更新
